// Mocks generated by Mockito 5.4.6 from annotations
// in organista/test/cubits/add_edit_music_sheet_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:cloud_firestore/cloud_firestore.dart' as _i2;
import 'package:firebase_storage/firebase_storage.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:organista/models/internal/music_sheet_file.dart' as _i12;
import 'package:organista/models/music_sheets/media_type.dart' as _i8;
import 'package:organista/models/music_sheets/music_sheet.dart' as _i9;
import 'package:organista/models/playlists/playlist.dart' as _i7;
import 'package:organista/models/repositories/repository.dart' as _i10;
import 'package:organista/repositories/firebase_firestore_repository.dart' as _i4;
import 'package:organista/repositories/firebase_storage_repository.dart' as _i11;
import 'package:organista/services/auth/auth_user.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeFirebaseFirestore_0 extends _i1.SmartFake implements _i2.FirebaseFirestore {
  _FakeFirebaseFirestore_0(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeListResult_1 extends _i1.SmartFake implements _i3.ListResult {
  _FakeListResult_1(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeReference_2 extends _i1.SmartFake implements _i3.Reference {
  _FakeReference_2(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

/// A class which mocks [FirebaseFirestoreRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseFirestoreRepository extends _i1.Mock implements _i4.FirebaseFirestoreRepository {
  MockFirebaseFirestoreRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FirebaseFirestore get instance =>
      (super.noSuchMethod(
            Invocation.getter(#instance),
            returnValue: _FakeFirebaseFirestore_0(
              this,
              Invocation.getter(#instance),
            ),
          )
          as _i2.FirebaseFirestore);

  @override
  _i5.Future<void> createUserDocument({required _i6.AuthUser? user}) =>
      (super.noSuchMethod(
            Invocation.method(#createUserDocument, [], {#user: user}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> deleteUser({required String? userId}) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUser, [], {#userId: userId}),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Stream<_i7.Playlist> getPlaylistStream(String? playlistId) =>
      (super.noSuchMethod(
            Invocation.method(#getPlaylistStream, [playlistId]),
            returnValue: _i5.Stream<_i7.Playlist>.empty(),
          )
          as _i5.Stream<_i7.Playlist>);

  @override
  _i5.Stream<Iterable<_i7.Playlist>> getPlaylistsStream(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getPlaylistsStream, [userId]),
            returnValue: _i5.Stream<Iterable<_i7.Playlist>>.empty(),
          )
          as _i5.Stream<Iterable<_i7.Playlist>>);

  @override
  _i5.Future<bool> addNewPlaylist({
    required String? playlistName,
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addNewPlaylist, [], {
              #playlistName: playlistName,
              #userId: userId,
            }),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> renamePlaylist({
    required String? newPlaylistName,
    required _i7.Playlist? playlist,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#renamePlaylist, [], {
              #newPlaylistName: newPlaylistName,
              #playlist: playlist,
            }),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> deletePlaylist({required _i7.Playlist? playlist}) =>
      (super.noSuchMethod(
            Invocation.method(#deletePlaylist, [], {#playlist: playlist}),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> uploadMusicSheetRecord({
    required String? fileName,
    required String? userId,
    required _i3.Reference? reference,
    required _i8.MediaType? mediaType,
    required String? repositoryId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadMusicSheetRecord, [], {
              #fileName: fileName,
              #userId: userId,
              #reference: reference,
              #mediaType: mediaType,
              #repositoryId: repositoryId,
            }),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> addMusicSheetsToPlaylist({
    required _i7.Playlist? playlist,
    required List<_i9.MusicSheet>? musicSheets,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addMusicSheetsToPlaylist, [], {
              #playlist: playlist,
              #musicSheets: musicSheets,
            }),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> renameMusicSheetInPlaylist({
    required _i9.MusicSheet? musicSheet,
    required String? fileName,
    required _i7.Playlist? playlist,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#renameMusicSheetInPlaylist, [], {
              #musicSheet: musicSheet,
              #fileName: fileName,
              #playlist: playlist,
            }),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> deleteMusicSheetInPlaylist({
    required _i9.MusicSheet? musicSheet,
    required _i7.Playlist? playlist,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMusicSheetInPlaylist, [], {
              #musicSheet: musicSheet,
              #playlist: playlist,
            }),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> musicSheetReorder({required _i7.Playlist? playlist}) =>
      (super.noSuchMethod(
            Invocation.method(#musicSheetReorder, [], {#playlist: playlist}),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> deleteMusicSheetFromRepository({
    required _i9.MusicSheet? musicSheet,
    required String? repositoryId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMusicSheetFromRepository, [], {
              #musicSheet: musicSheet,
              #repositoryId: repositoryId,
            }),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Stream<Iterable<_i10.Repository>> getRepositoriesStream({
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getRepositoriesStream, [], {#userId: userId}),
            returnValue: _i5.Stream<Iterable<_i10.Repository>>.empty(),
          )
          as _i5.Stream<Iterable<_i10.Repository>>);

  @override
  _i5.Stream<Iterable<_i9.MusicSheet>> getRepositoryMusicSheetsStream(
    String? repositoryId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getRepositoryMusicSheetsStream, [repositoryId]),
            returnValue: _i5.Stream<Iterable<_i9.MusicSheet>>.empty(),
          )
          as _i5.Stream<Iterable<_i9.MusicSheet>>);

  @override
  _i5.Future<bool> createGlobalRepository({required String? name}) =>
      (super.noSuchMethod(
            Invocation.method(#createGlobalRepository, [], {#name: name}),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<int> getUserRepositoriesCount({required String? userId}) =>
      (super.noSuchMethod(
            Invocation.method(#getUserRepositoriesCount, [], {#userId: userId}),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<bool> createUserRepository({
    required String? userId,
    required String? name,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createUserRepository, [], {
              #userId: userId,
              #name: name,
            }),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> renameRepository({
    required String? repositoryId,
    required String? newName,
    required String? currentUserId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#renameRepository, [], {
              #repositoryId: repositoryId,
              #newName: newName,
              #currentUserId: currentUserId,
            }),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> deleteRepository({
    required String? repositoryId,
    required String? currentUserId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRepository, [], {
              #repositoryId: repositoryId,
              #currentUserId: currentUserId,
            }),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<int> getRepositoryMusicSheetsCount(String? repositoryId) =>
      (super.noSuchMethod(
            Invocation.method(#getRepositoryMusicSheetsCount, [repositoryId]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);
}

/// A class which mocks [FirebaseStorageRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseStorageRepository extends _i1.Mock implements _i11.FirebaseStorageRepository {
  MockFirebaseStorageRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.ListResult> listFolderContents(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#listFolderContents, [path]),
            returnValue: _i5.Future<_i3.ListResult>.value(
              _FakeListResult_1(
                this,
                Invocation.method(#listFolderContents, [path]),
              ),
            ),
          )
          as _i5.Future<_i3.ListResult>);

  @override
  _i5.Future<void> deleteFolder(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#deleteFolder, [path]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i3.Reference getReference(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#getReference, [path]),
            returnValue: _FakeReference_2(
              this,
              Invocation.method(#getReference, [path]),
            ),
          )
          as _i3.Reference);

  @override
  _i5.Future<_i3.Reference?> uploadFile({
    required _i12.MusicSheetFile? file,
    required String? bucket,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadFile, [], {#file: file, #bucket: bucket}),
            returnValue: _i5.Future<_i3.Reference?>.value(),
          )
          as _i5.Future<_i3.Reference?>);
}
