// Mocks generated by Mockito 5.4.6 from annotations
// in organista/test/features/show_playlist/bloc/playlist_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:firebase_storage/firebase_storage.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:organista/models/music_sheets/media_type.dart' as _i7;
import 'package:organista/models/music_sheets/music_sheet.dart' as _i8;
import 'package:organista/models/playlists/playlist.dart' as _i5;
import 'package:organista/models/repositories/repository.dart' as _i9;
import 'package:organista/repositories/firebase_firestore_repository.dart' as _i2;
import 'package:organista/services/auth/auth_user.dart' as _i4;
import 'package:organista/services/export_playlist/export_playlist_service.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [FirebaseFirestoreRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseFirestoreRepository extends _i1.Mock implements _i2.FirebaseFirestoreRepository {
  MockFirebaseFirestoreRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> createUserDocument({required _i4.AuthUser? user}) =>
      (super.noSuchMethod(
            Invocation.method(#createUserDocument, [], {#user: user}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> deleteUser({required String? userId}) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUser, [], {#userId: userId}),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Stream<_i5.Playlist> getPlaylistStream(String? playlistId) =>
      (super.noSuchMethod(
            Invocation.method(#getPlaylistStream, [playlistId]),
            returnValue: _i3.Stream<_i5.Playlist>.empty(),
          )
          as _i3.Stream<_i5.Playlist>);

  @override
  _i3.Stream<Iterable<_i5.Playlist>> getPlaylistsStream(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getPlaylistsStream, [userId]),
            returnValue: _i3.Stream<Iterable<_i5.Playlist>>.empty(),
          )
          as _i3.Stream<Iterable<_i5.Playlist>>);

  @override
  _i3.Future<bool> addNewPlaylist({
    required String? playlistName,
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addNewPlaylist, [], {
              #playlistName: playlistName,
              #userId: userId,
            }),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> renamePlaylist({
    required String? newPlaylistName,
    required _i5.Playlist? playlist,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#renamePlaylist, [], {
              #newPlaylistName: newPlaylistName,
              #playlist: playlist,
            }),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> deletePlaylist({required _i5.Playlist? playlist}) =>
      (super.noSuchMethod(
            Invocation.method(#deletePlaylist, [], {#playlist: playlist}),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> uploadMusicSheetRecord({
    required String? fileName,
    required String? userId,
    required _i6.Reference? reference,
    required _i7.MediaType? mediaType,
    required String? repositoryId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadMusicSheetRecord, [], {
              #fileName: fileName,
              #userId: userId,
              #reference: reference,
              #mediaType: mediaType,
              #repositoryId: repositoryId,
            }),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> addMusicSheetsToPlaylist({
    required _i5.Playlist? playlist,
    required List<_i8.MusicSheet>? musicSheets,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addMusicSheetsToPlaylist, [], {
              #playlist: playlist,
              #musicSheets: musicSheets,
            }),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  bool renameMusicSheetInPlaylist({
    required _i8.MusicSheet? musicSheet,
    required String? fileName,
    required _i5.Playlist? playlist,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#renameMusicSheetInPlaylist, [], {
              #musicSheet: musicSheet,
              #fileName: fileName,
              #playlist: playlist,
            }),
            returnValue: false,
          )
          as bool);

  @override
  _i3.Future<bool> deleteMusicSheetInPlaylist({
    required _i8.MusicSheet? musicSheet,
    required _i5.Playlist? playlist,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMusicSheetInPlaylist, [], {
              #musicSheet: musicSheet,
              #playlist: playlist,
            }),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> musicSheetReorder({required _i5.Playlist? playlist}) =>
      (super.noSuchMethod(
            Invocation.method(#musicSheetReorder, [], {#playlist: playlist}),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> deleteMusicSheetFromRepository({
    required _i8.MusicSheet? musicSheet,
    required String? repositoryId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMusicSheetFromRepository, [], {
              #musicSheet: musicSheet,
              #repositoryId: repositoryId,
            }),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Stream<Iterable<_i9.Repository>> getRepositoriesStream({
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getRepositoriesStream, [], {#userId: userId}),
            returnValue: _i3.Stream<Iterable<_i9.Repository>>.empty(),
          )
          as _i3.Stream<Iterable<_i9.Repository>>);

  @override
  _i3.Stream<Iterable<_i8.MusicSheet>> getRepositoryMusicSheetsStream(
    String? repositoryId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getRepositoryMusicSheetsStream, [repositoryId]),
            returnValue: _i3.Stream<Iterable<_i8.MusicSheet>>.empty(),
          )
          as _i3.Stream<Iterable<_i8.MusicSheet>>);

  @override
  _i3.Future<bool> createGlobalRepository({required String? name}) =>
      (super.noSuchMethod(
            Invocation.method(#createGlobalRepository, [], {#name: name}),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<int> getUserRepositoriesCount({required String? userId}) =>
      (super.noSuchMethod(
            Invocation.method(#getUserRepositoriesCount, [], {#userId: userId}),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<bool> createUserRepository({
    required String? userId,
    required String? name,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createUserRepository, [], {
              #userId: userId,
              #name: name,
            }),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> renameRepository({
    required String? repositoryId,
    required String? newName,
    required String? currentUserId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#renameRepository, [], {
              #repositoryId: repositoryId,
              #newName: newName,
              #currentUserId: currentUserId,
            }),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> deleteRepository({
    required String? repositoryId,
    required String? currentUserId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRepository, [], {
              #repositoryId: repositoryId,
              #currentUserId: currentUserId,
            }),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<int> getRepositoryMusicSheetsCount(String? repositoryId) =>
      (super.noSuchMethod(
            Invocation.method(#getRepositoryMusicSheetsCount, [repositoryId]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);
}

/// A class which mocks [ExportPlaylistService].
///
/// See the documentation for Mockito's code generation for more information.
class MockExportPlaylistService extends _i1.Mock implements _i10.ExportPlaylistService {
  MockExportPlaylistService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String?> exportPlaylistToPdf({required _i5.Playlist? playlist}) =>
      (super.noSuchMethod(
            Invocation.method(#exportPlaylistToPdf, [], {#playlist: playlist}),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);
}
