name: Tests

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Extract Flutter version
      id: flutter_version
      run: |
        # Extract Flutter version from pubspec.yaml
        FLUTTER_VERSION=$(grep -o 'flutter:.*' pubspec.yaml | head -1 | sed 's/flutter://' | tr -d ' ')
        if [ -z "$FLUTTER_VERSION" ]; then
          echo "Error: Flutter version not specified in pubspec.yaml"
          echo "Please add flutter version constraint to your pubspec.yaml dependencies"
          exit 1
        fi
        echo "flutter_version=$FLUTTER_VERSION" >> $GITHUB_OUTPUT
        echo "Using Flutter version: $FLUTTER_VERSION"

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ steps.flutter_version.outputs.flutter_version }}
        channel: stable
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Verify formatting
      run: |
        find . -name "*.dart" -not -path "./lib/l10n/*" | xargs dart format --line-length=120 --output=none --set-exit-if-changed
    
    - name: Copy credentials and analyze
      run: |
        cp assets/config/credentials.example.json assets/config/credentials.json
        flutter analyze
    
    - name: Run tests
      run: flutter test --coverage
    
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}